### ISSUE TITLE
"Cannot edit Range" Error

### ISSUE THREAD

**Issue by tomyan112** [Chem4Word/Version3-2#36]
**Describe the bug**
"Cannot edit Range" Error

**To Reproduce**
Steps to reproduce the behaviour:
1. Draw something on 2 different word document
2.  While it is calculating
![image](https://user-images.githubusercontent.com/9064351/156908131-27dd9295-24c2-4565-b190-5ee7f2b25c5c.png)

4. Click a Chem4Word equation in another document
6. See error

**Screenshot**
![image](https://user-images.githubusercontent.com/9064351/156908113-812dbb94-0e66-401c-9708-9a2e598570f2.png)

**Desktop (please complete the following information):**
Chem4Word beta 2

**Comment by MikeWilliams-UK** [comment]
@tomyan112 Thanks for the excellent description of the bug, which is one that has been present sinve V3.0 and nobody has yet reported it to us either here or in our Facebook group for support.

I now have something to look into, from your description I can see that our use of ActiveDocument property of the word application might be the issue here as it quite clearly will have changed with the scenario you have described.

**Comment by MikeWilliams-UK** [comment]
@deadlyvices it was as I now suspected caused by using Application.ActiveDocument which in this scenario changes during the rendering process.

I am going to review the use of Application.ActiveDocument to see if I can find any more gotchas before raising internal pull request.

**Comment by MikeWilliams-UK** [comment]
Many thanks for describing the scenario @tomyan112 the target release for this is V3.2.3

**Comment by MikeWilliams-UK** [comment]
Included in V3.2.3 Beta 3
